### ISSUE TITLE
Bugs in cNFT

### ISSUE THREAD

**Issue by achrafismyname** [curaOS/contracts#48]
I'll use this issue to keep track of bugs I found in cNFT while sandbox testing:
  

## View methods are considered a change method by NEAR 
I found this first with `nft_tokens_for_owner`, then it happened for me too with `nft_metadata`
([error log](https://github.com/curaOS/contracts/runs/4788086653?check_suite_focus=true#step:9:12)) 

## Calling `init` doesn't update contract metadata 
`init` method is supposed to update the contract metadata but that's not happening

Steps to reproduce:
  - Build cNFT
  - Deploy to a new address
  - Call `init` method with new metadata ([example](https://explorer.testnet.near.org/transactions/37b2Nya2gJZyEGSaGcLezB1G7NLmAyHA1GpMEg4WEx1B))
  - Call `nft_metadata` ([example results](https://explorer.testnet.near.org/transactions/BDfPCDeA8eNAbP14aX6npXAcMbogjDUDTeqjndaHgDoP))

## Associated PR's

- [ ] #58 
- [ ] #59

**Comment by AshenI99** [comment]
@achrafismyname  I think all the view methods are considered as change methods. Because all the `enumeration` methods,  `nft_token` method and `nft_metadata` method are not executing successfully with `near view`.

**Comment by achrafismyname** [comment]
> @achrafismyname I think all the view methods are considered as change methods. Because all the `enumeration` methods, `nft_token` method and `nft_metadata` method are not executing successfully with `near view`.

Yeah but that shouldn't happen because we are not changing any data from the blockchain.
My guess for the cause is that the methods are use too much proccessing power which require more gas than usual view methods.

**Comment by AshenI99** [comment]
> > @achrafismyname I think all the view methods are considered as change methods. Because all the `enumeration` methods, `nft_token` method and `nft_metadata` method are not executing successfully with `near view`.
> 
> Yeah but that shouldn't happen because we are not changing any data from the blockchain. My guess for the cause is that the methods are use too much proccessing power which require more gas than usual view methods.

Yeah. That makes sense. I’ll look into that.

**Comment by achrafismyname** [comment]
Hey @devey, there is probably a problem with the current structure which is causing all methods to be considered a call method

The constructor of the persistent models gets excuted in every calls to the contract even if the method called has nothing to do with it because of the line below
https://github.com/curaOS/contracts/blob/357feb3e726aba2a0d2548b2ca72a1331641264e/as/cNFT/assembly/models/persistent_tokens.ts#L146
This causes the script to try to write to storage, which makes the current structure not inefficient and makes view methods fail

@AshenI99 tried a in https://github.com/curaOS/contracts/pull/47/commits/966e3419216e29e6b79b07c706ee5803e4706905 This solves the issue and the view methods gets called as a view method but not what would be the best approach to fix this

**Comment by AshenI99** [comment]
Hi, @devey Other than the above method, we can use a function for every persistent model to return the object. For an example, like this for `persistent_tokens` model.

```
export function init(): <PersistentTokens> {
   let persistent_tokens = new PersistentTokens('pt');
   return persistent_tokens;
}
```

In this way, we can prevent executing these functions for every request. What do you think ?

**Comment by AshenI99** [comment]
Hey @achrafismyname, 

I think I have figured why `init` function is not updating contract metadata. Since below line is not a function, it is executing every time when we call or view a method. So when we call `init` function, it does update the contract metadata. But it is replacing from `defaultNFTContractMetadata()` in the next request we make to the smart contract. So default parameters gets replaced with actual values.

https://github.com/curaOS/contracts/blob/357feb3e726aba2a0d2548b2ca72a1331641264e/as/cNFT/assembly/models/persistent_nft_contract_metadata.ts#L65-L66

So the fix is the either one of two methods we have mentioned above regarding call methods. I have a made a fix here #59.

**Comment by devey** [comment]
@achrafismyname @AshenI99 just saw this. Interesting! The pattern on initializing persistent structure directly on contract deploy is something I picked up while learning about AS on NEAR ([see here for example](https://github.com/Learn-NEAR/NCD.L1.sample--nearly-neighbors/blob/c4fa4934b13100309f558f6dc2e099123645814a/src/factory/assembly/index.ts)). If this is the problem I think we can move:
```
export const persistent_tokens = new PersistentTokens('pt') 
```
directly into a contract `init`. Sounds good?

Maybe unrelated but have you tried removing `@nearBindgen` from `PersistentToken`? I think if the structure is only internal it might not be necessary.

**Comment by AshenI99** [comment]
> Maybe unrelated but have you tried removing `@nearBindgen` from `PersistentToken`? I think if the structure is only internal it might not be necessary.

Hi, @devey Removing `@nearBindgen` is not fixing the issue. :-(
