### ISSUE TITLE
cNFT security

### ISSUE THREAD

**Issue by 0x5CE** [curaOS/contracts#55]
- [x] #57 
- [x] #72 
- [x] #71 
- [x] #83

### Reference Implementations
- [x] https://github.com/ParasHQ/paras-nft-contract/blob/main/paras-nft-contract
- [x] https://github.com/near-examples/nft-tutorial

**Comment by devey** [comment]
- don't use `signer_id` but `predecessor_account_id`; this ensures account can only act on caller's behalf inside the smart contract and not on signer's behalf (that might be hidden behind a cross contract call)

**Comment by achrafismyname** [comment]
- nft_transfer: 
  - caller should be owner or authorized to transfer
  - bidder_id should not be already owner of token_id
  - remove token first then add it to new owner (if nft_transfer gets called twice at the same time, there is a low chance, it gets added to two accounts)
  - after remove make sure old owner doesn't have token 

- bid:
  - the bid amount should never be zero
  - the bid amount should be splitatble perfectly into all the bid shares
  - the bid amount should be equal to deposit amount
  - If already has bid refund the first bid then add new bid

- bidShares:
  - the total of all shares should be equal to 100

- ask:
  - the asked amount should never be zero
  - the asked amount should be splitatble perfectly into all the bid shares
