### ISSUE TITLE
`accept_bid` is not working when running through `BSCS` project

### ISSUE THREAD

**Issue by AshenI99** [curaOS/contracts#86]
## `accept_bid` Issues

- `accept_bid` is not working when executing it through `BSCS` project. Getting the following errors.

1. `"ExecutionError":"WebAssembly trap: Memory out of bounds trap."`
2. `"ExecutionError": "Smart contract panicked: Cannot parse JSON"`
3. `"ExecutionError": "Smart contract panicked: You must own token"`
4. `"ExecutionError": "Smart contract panicked: Key does not exist"`

- [ ] #93 **(Error 1, 2 & 4)**
- [x] #95 **(Error 3)**

**Comment by devey** [comment]
#98

**Comment by devey** [comment]
@AshenI99 could you be more specific on how to reproduce these? Which call to `BSCS` throws the errors?

**Comment by AshenI99** [comment]
@devey These errors were not visible when we running contract tests in sandbox mode. These errors showed up while testing the contract through BSCS project. So these happened due to the bugs in the contract.
