### ISSUE TITLE
Add sandbox tests for market methods

### ISSUE THREAD

**Issue by achrafismyname** [curaOS/contracts#87]
Some methods from market are not test, and we need to add them 
https://github.com/curaOS/contracts/blob/ee70409a37821b583faf5d2704a4319649504970/tests/cNFT.js#L309

**Comment by devey** [comment]
True, I would just put this directly into `workspace-js` folder after We moved the tests.

**Comment by devey** [comment]
@achrafismyname does #90 close this too?

**Comment by achrafismyname** [comment]
Yes
