### ISSUE TITLE
Minify Creative Code saved in contract

### ISSUE THREAD

**Issue by devey** [curaOS/contracts#89]

**Comment by devey** [comment]
Thanks for looking into it @achrafismyname.

Could you describe how this representation of the script is created?
https://github.com/curaOS/BSCS/blob/45d4335e92ab63281ebe5e94511ec4b25696ba68/packages/scripts/metadata.json#L9

**Comment by achrafismyname** [comment]
I used https://minify-js.com/
It compiles the code to a simpler structure and minify it
