### ISSUE TITLE
Asserts checks are failing when accessing `nft_transfer` through `accept_bid`

### ISSUE THREAD

**Issue by AshenI99** [curaOS/contracts#95]
## Problem

- When accepting a bid, we are calling `nft_transfer` as a cross contract call to transfer the token to the new owner.

https://github.com/curaOS/contracts/blob/c3dbcb077dd03ecb6663d420273007903c53ea9b/as/cNFT/assembly/market.ts#L229

- When it comes to `nft_transfer` function, there is an assert for check that the owner of the token is the one who signed the transaction. It allows to pass the `owner_id` of the token and `accountId` of the `predecessor`. If those are not equal, it will throw an error.

https://github.com/curaOS/contracts/blob/c3dbcb077dd03ecb6663d420273007903c53ea9b/as/cNFT/assembly/core.ts#L54-L65
https://github.com/curaOS/contracts/blob/c3dbcb077dd03ecb6663d420273007903c53ea9b/as/cNFT/assembly/utils/asserts.ts#L59-L64</br>
- According to the near-sdk-as [(check here)](https://github.com/near/near-sdk-as/blob/f3707a1672d6da6f6d6a75cd645f8cbdacdaf495/sdk-core/assembly/contract.ts#L34), when we just calling only the `nft_transfer` function without another functions, it takes Id of the account who signed the transaction as the, `context.predecessor`. But when we are calling `nft_transfer` function from the `accept_bid`, it takes the id of the contract who called the `nft_transfer` function as the, `context.predecessor`. 

- As an example, assume a contract is stored in `alice.test.near`, and a user `jenny.test.near`, calls the `nft_transfer` function to transfer a token to another user in the contract. In that case `context.predecessor` is equal to `jenny.test.near`, because it is a transaction. Assume `jenny.test.near` accepts a bid made by another user in the contract. In that case when calling `nft_transfer` function from the `accept_bid` method, `context.predecessor` is equal to `alice.test.near`. Which is the Id of the contract. Because it is a cross contract call made by the contract itself.

## Solutions

1. Simple solution would be just change the `assert_eq_token_owner` function to pass when `context.predecessor` is equal to contract Id itself. 
2. Another one would be add two functions like `nft_transfer` and `internal_nft_transfer` and add assert check to `nft_transfer`. Then use `internal_nft_transfer` inside the `accept_bid` method. That way we can bypass the assert check when calling transfer function from the inside the contract. That way we lost `nft_transfer log` when calling it from the `accept_bid` method. But still we can use `accept_bid log` to capture that event.
3. Another one would be add approval management system, where add the contract Id to the token `approvalIDs` map when minting a token. And then change assert check to pass it when the `context.predecessor` is in the `approvalIDs` map for that particular token.

**Comment by AshenI99** [comment]
> ## Problem
> * When accepting a bid, we are calling `nft_transfer` as a cross contract call to transfer the token to the new owner.
> 
> https://github.com/curaOS/contracts/blob/c3dbcb077dd03ecb6663d420273007903c53ea9b/as/cNFT/assembly/market.ts#L229
> 
> * When it comes to `nft_transfer` function, there is an assert for check that the owner of the token is the one who signed the transaction. It allows to pass the `owner_id` of the token and `accountId` of the `predecessor`. If those are not equal, it will throw an error.
> 
> https://github.com/curaOS/contracts/blob/c3dbcb077dd03ecb6663d420273007903c53ea9b/as/cNFT/assembly/core.ts#L54-L65
> 
> 
> https://github.com/curaOS/contracts/blob/c3dbcb077dd03ecb6663d420273007903c53ea9b/as/cNFT/assembly/utils/asserts.ts#L59-L64
> 
> 
> * According to the near-sdk-as [(check here)](https://github.com/near/near-sdk-as/blob/f3707a1672d6da6f6d6a75cd645f8cbdacdaf495/sdk-core/assembly/contract.ts#L34), when we just calling only the `nft_transfer` function without another functions, it takes Id of the account who signed the transaction as the, `context.predecessor`. But when we are calling `nft_transfer` function from the `accept_bid`, it takes the id of the contract who called the `nft_transfer` function as the, `context.predecessor`.
> * As an example, assume a contract is stored in `alice.test.near`, and a user `jenny.test.near`, calls the `nft_transfer` function to transfer a token to another user in the contract. In that case `context.predecessor` is equal to `jenny.test.near`, because it is a transaction. Assume `jenny.test.near` accepts a bid made by another user in the contract. In that case when calling `nft_transfer` function from the `accept_bid` method, `context.predecessor` is equal to `alice.test.near`. Which is the Id of the contract. Because it is a cross contract call made by the contract itself.
> 
> ## Solutions
> 1. Simple solution would be just change the `assert_eq_token_owner` function to pass when `context.predecessor` is equal to contract Id itself.
> 2. Another one would be add two functions like `nft_transfer` and `internal_nft_transfer` and add assert check to `nft_transfer`. Then use `internal_nft_transfer` inside the `accept_bid` method. That way we can bypass the assert check when calling transfer function from the inside the contract. That way we lost `nft_transfer log` when calling it from the `accept_bid` method. But still we can use `accept_bid log` to capture that event.
> 3. Another one would be add approval management system, where add the contract Id to the token `approvalIDs` map when minting a token. And then change assert check to pass it when the `context.predecessor` is in the `approvalIDs` map for that particular token.

Hi guys @devey @achrafismyname , what do you think?

**Comment by devey** [comment]
Thanks for looking into this @AshenI99!

I think solution 3 is the best approach, to respect the standard and make sure the contract is already set to support [Approval Management](https://nomicon.io/Standards/NonFungibleToken/ApprovalManagement) integration.

You can see how all of these methods are implemented in the `NFT` contract although we don't need all of them.

The most relevant parts are adding `approvals` to our token:
https://github.com/curaOS/contracts/blob/8cd403838047b36e936033f5a75e4ff7401f6c3a/as/NFT/assembly/models.ts#L30

and on mint, add minter contract to the approvals above (leave `next_approval_id` to one as this only gets +1 if `nft_approve` was implemented):
https://github.com/curaOS/contracts/blob/d5a9a3e358fcce98256104273d70e3406ef9afea/as/NFT/assembly/index.ts#L265

and lastly, integrate the `nft_is_approved` function in `cNFT`:
https://github.com/curaOS/contracts/blob/d5a9a3e358fcce98256104273d70e3406ef9afea/as/NFT/assembly/index.ts#L295

You can then call `nft_is_approved(token_id, context.predecessor, 1)` from `nft_transfer` function to make sure only contract can transfer.

Does that make sense?
